apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - source.yaml
  - library-pvc.yaml
  - postgres.yaml
  - release.yaml
  - httproute.yaml
  - tailscale-ingress.yaml
