apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvmm
  namespace: default
  labels:
    app: kvmm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvmm
  template:
    metadata:
      labels:
        app: kvmm
    spec:
      containers:
        - name: kvmm
          image: ghcr.io/rothgar/kvmm:v0.2.2
          args:
            - server
            - -config
            - /config/config.toml
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kvmm-config
