apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvmm
  namespace: default
  labels:
    app: kvmm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvmm
  template:
    metadata:
      labels:
        app: kvmm
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kvmm
          image: ghcr.io/rothgar/kvmm:0.2.4
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args:
            - server
            - -config
            - /config/config.toml
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: thumbnails
              mountPath: /config/thumbnails
      volumes:
        - name: config
          configMap:
            name: kvmm-config
        - name: thumbnails
          emptyDir:
            sizeLimit: 10Mi
