apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - source.yaml
  - release.yaml
  - values-configmap.yaml
  - http-config.yaml
  - httproute.yaml
  - tailscale-ingress.yaml
