apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - dcgm-exporter
  - descheduler
  - external-dns
  - flannel
  - flux-system
  - frigate
  - headlamp
  - home-assistant
  - immich
  - kubelet-csr-approver
  - kvmm
  - local-path-provisioner
  - metallb
  - metrics-server
  - miniflux
  - monitoring
  - mqtt
  - nfs-csi
  - nvidia-system
  - ollama
  - reaparr
  - reloader
  - tailscale-operator
  - traefik
