apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - metallb
  - monitoring
  - local-path-provisioner
  - kvmm
  - home-assistant
  - nvidia-system
  - dcgm-exporter
