config: |
  mqtt:
    enabled: true
    host: "mosquitto.mqtt.svc.cluster.local"
    port: 1883
  detectors:
    tensorrt:
      type: tensorrt
  cameras:
    front_door:
      ffmpeg:
        inputs:
          - path: rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.60:554/h264Preview_01_main
            roles:
              - detect
              - record
      detect:
        enabled: true
    rear_door:
      ffmpeg:
        inputs:
          - path: rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.62:554/h264Preview_01_main
            roles:
              - detect
              - record
      detect:
        enabled: true
    backyard:
      ffmpeg:
        inputs:
          - path: rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.61:554/h264Preview_01_main
            roles:
              - detect
              - record
      detect:
        enabled: true
