config: |
  mqtt:
    enabled: true
    host: "mosquitto.mqtt.svc.cluster.local"
    port: 1883
  cameras:
    # Define at least one camera
    front_door:
      ffmpeg:
        inputs:
          - path: rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.60:554/h264Preview_01_main
            roles:
              - record
    rear_door:
      ffmpeg:
        inputs:
          - path: rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.62:554/h264Preview_01_main
            roles:
              - record
    backyard:
      ffmpeg:
        inputs:
          - path: rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.61:554/h264Preview_01_main
            roles:
              - record
