apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux-tailscale
  namespace: miniflux
spec:
  ingressClassName: tailscale
  rules:
    - host: miniflux
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: miniflux
                port:
                  number: 8080
  tls:
    - hosts:
        - miniflux
